default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>
  host: localhost
  port: 5432
  database: biblioteca
  username: openpg
  password: openpgpwd

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
